"""Write the Slurm jobs that rerun HBM_DESIGN runs at their required code distance.

analyze.py flags a row rerun_needed when the code distance it needs (d_req) changes the
recharge steps or the factory size used in the simulation (which ran at HBM_D). This
groups those rows by (design, source rounds, d_req), skips any that already have a run at
that d, writes one benchmark list per group to revision/lists/ and prints one sbatch
array command per group.

Usage (from test/):
  python ../scripts/revision/make_reruns.py rev.csv --pprime 1 5 > revision/reruns.sh
  cat revision/reruns.sh && bash revision/reruns.sh
"""

import argparse
import csv
import glob
import os
import sys
from collections import defaultdict


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("csv", help="output of analyze.py")
    ap.add_argument("--pprime", type=float, nargs="+", default=[1, 5],
                    help="only rerun rows for these p' multiples")
    ap.add_argument("--lists", default="revision/lists",
                    help="dir with the benchmark lists written by submit_revision.sh")
    args = ap.parse_args()

    paths = {}
    for lst in glob.glob(os.path.join(args.lists, "*.txt")):
        with open(lst) as f:
            for line in f:
                line = line.strip()
                if line:
                    paths.setdefault(os.path.basename(line)[:-len(".qasm")], line)

    with open(args.csv) as f:
        rows = [r for r in csv.DictReader(f) if r.get("status") == "ok"]
    done = {(r["bench"], r["spec"], r["recharge_rounds"], r["d_sim"]) for r in rows}

    groups = defaultdict(set)
    for r in rows:
        if r.get("rerun_needed") != "True" or not r.get("d_req"):
            continue
        if float(r["pprime_mult"]) not in args.pprime:
            continue
        d_req = str(int(float(r["d_req"])))
        if (r["bench"], r["spec"], r["recharge_rounds"], d_req) in done:
            continue
        groups[(r["spec"], r["source"], r["recharge_rounds"], d_req)].add(r["bench"])

    print("#!/bin/bash")
    print("# Generated by make_reruns.py; run from test/.")
    print("set -euo pipefail")
    for (spec, source, rounds, d), benches in sorted(groups.items()):
        missing = sorted(b for b in benches if b not in paths)
        if missing:
            print(f"# skipped (not found in {args.lists}): {missing}", file=sys.stderr)
        found = sorted(paths[b] for b in benches if b in paths)
        if not found:
            continue
        rounds = str(int(float(rounds)))
        list_path = os.path.join(args.lists, f"rerun_{spec}_R{rounds}_d{d}.txt")
        with open(list_path, "w") as f:
            f.write("\n".join(found) + "\n")
        src_var = "HBM_CULT_ROUNDS" if source == "cultivation" else "HBM_FACTORY_ROUNDS"
        print(f"sbatch --array=0-{len(found) - 1} --job-name=rerun-{spec}-d{d} "
              f"--export=ALL,DESIGN={spec},BENCH_LIST={list_path},HBM_D={d},"
              f"{src_var}={rounds} revision/run_design.sh")
    print(f"# {sum(len(b) for b in groups.values())} reruns in {len(groups)} arrays",
          file=sys.stderr)


if __name__ == "__main__":
    main()
